#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker2"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "6de73c3a4d134668bd85fcea801fc749" }
]
